#wap to take 8 numbers as input and store them in a set
s=set()
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
n=input("enter the number:")
s.add(int(n))
print(s)