#wap to create a dictionary with names and languages
d={}
name=input("Enter your name: ")
language=input("Enter your language: ")
d.update({name: language})
name=input("Enter your name: ")
language=input("Enter your language: ")
d.update({name: language})
name=input("Enter your name: ")
language=input("Enter your language: ")
d.update({name: language})
name=input("Enter your name: ")
language=input("Enter your language: ")
d.update({name: language})
print(d)